version: "3.8"

services:
  db:
    container_name: gomin_db
    image: postgres:15.2
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: gomin
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d gomin"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
    container_name: gomin_api
    depends_on:
      - db
    ports:
      - '1323:1323'
    restart: always
    environment:
      # Must be prefixed with APP_
      # See pkg/common/config/config.go and viper for more details
      - APP_DB_URL=postgres://test:test@gomin_db:5432/gomin
      - APP_PORT=1323
